spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_management_system?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
